# arguments.multiple.value.py
def func(a, b, c):
	print(a, b, c)

func(2, 3, a = 1) # should throw an error